name: Build SHRP

on:
  workflow_dispatch:
    inputs:
      MANIFEST_URL:
        description: Manifest URL
        required: true
        default: 'https://github.com/SHRP-Reborn/manifest.git'
      MANIFEST_BRANCH:
        description: Manifest Branch
        required: true
        default: 'shrp-12.1'
      DEVICE_TREE_URL:
        description: Device Tree URL
        required: true
        default: 'https://github.com/saadelasfur/shrp_device_samsung_m52xq.git'
      DEVICE_TREE_BRANCH:
        description: Device Tree Branch
        required: true
        default: 'shrp_12.1'
      DEVICE_PATH:
        description: Device Path
        required: true
        default: 'device/samsung/m52xq'
      DEVICE_NAME:
        description: Device Name
        required: true
        default: 'm52xq'
      MAKEFILE_NAME:
        description: Makefile Name
        required: true
        default: 'twrp_m52xq'
      BUILD_TARGET:
        description: Build Target
        required: true
        default: 'recovery'
      SHRP_VERSION:
        description: SHRP Version
        required: true
        default: 'v3.2_Stable'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Display Run Parameters
      run: |
        echo "::group::User Environment Variables"
        echo "Manifest URL: ${{ github.event.inputs.MANIFEST_URL }}"
        echo "Manifest Branch: ${{ github.event.inputs.MANIFEST_BRANCH }}"
        echo "Device Tree URL: ${{ github.event.inputs.DEVICE_TREE_URL }}"
        echo "Device Tree Branch: ${{ github.event.inputs.DEVICE_TREE_BRANCH }}"
        echo "Device Path: ${{ github.event.inputs.DEVICE_PATH }}"
        echo "Device Name: ${{ github.event.inputs.DEVICE_NAME }}"
        echo "Makefile Name: ${{ github.event.inputs.MAKEFILE_NAME }}"
        echo "Build Target: ${{ github.event.inputs.BUILD_TARGET }}.img"
        echo "SHRP Version: ${{ github.event.inputs.SHRP_VERSION }}"
        echo "::endgroup::"

    - name: Check Out
      uses: actions/checkout@v4

    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main

    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y
        DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
            linux-modules-extra-$(uname -r) \
            gperf gcc-multilib gcc-10-multilib g++-multilib g++-10-multilib \
            libc6-dev lib32ncurses-dev x11proto-core-dev libx11-dev tree lib32z-dev libgl1-mesa-dev libxml2-utils \
            xsltproc bc ccache lib32readline-dev lib32z1-dev liblz4-tool libncurses-dev libsdl1.2-dev \
            build-essential libgtk-3-dev libglu1-mesa-dev freeglut3-dev git libxml2 lzop pngcrush schedtool squashfs-tools \
            imagemagick libbz2-dev lzma ncftp qemu-user-static libstdc++-10-dev libncurses6 python3 tar

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'latest'

    - name: Install OpenJDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install repo
      run: |
        mkdir ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        sudo ln -sf ~/bin/repo /usr/bin/repo

    - name: Initialize repo
      run: |
        mkdir workspace
        cd workspace
        echo "workspace-folder=$(pwd)" >> $GITHUB_OUTPUT
        git config --global user.name "Saad"
        git config --global user.email "saadelasfur@gmail.com"
        repo init --depth=1 -u ${{ github.event.inputs.MANIFEST_URL }} -b ${{ github.event.inputs.MANIFEST_BRANCH }}
      id: pwd

    - name: Repo Sync
      run: |
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
      working-directory: workspace

    - name: Clone device tree
      run: |
        git clone ${{ github.event.inputs.DEVICE_TREE_URL }} -b ${{ github.event.inputs.DEVICE_TREE_BRANCH }} ./${{ github.event.inputs.DEVICE_PATH }}
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 12

    - name: Building recovery
      run: |
        export ALLOW_MISSING_DEPENDENCIES=true
        source build/envsetup.sh
        lunch ${{ github.event.inputs.MAKEFILE_NAME }}-eng && make clean && mka ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Set Date Variables
      run: |
        echo "DATE_SHORT=$(date +%Y%m%d)" >> $GITHUB_OUTPUT
        echo "DATE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
        echo "DATE_LONG=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
      id: date

    - name: Archive the files
      run: |
        ls -a ${{ steps.pwd.outputs.workspace-folder }}/out/target/product/ && echo
        ls -a ${{ steps.pwd.outputs.workspace-folder }}/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/ && echo
        cd out/target/product/${{ github.event.inputs.DEVICE_NAME }}
        tar -cvf SHRP_${{ github.event.inputs.SHRP_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}_${{ steps.date.outputs.DATE_SHORT }}.tar ${{ github.event.inputs.BUILD_TARGET }}.img
        mv ${{ github.event.inputs.BUILD_TARGET }}.img SHRP_${{ github.event.inputs.SHRP_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}_${{ steps.date.outputs.DATE_SHORT }}.img
        mv *AddonRescue*.zip AddonRescue_${{ github.event.inputs.SHRP_VERSION }}_${{ github.event.inputs.DEVICE_NAME }}-${{ steps.date.outputs.DATE_SHORT }}.zip
        mv SHRP*.zip SHRP_${{ github.event.inputs.SHRP_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}_${{ steps.date.outputs.DATE_SHORT }}.zip
      working-directory: ${{ steps.pwd.outputs.workspace-folder }}

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: | 
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/SHRP_${{ github.event.inputs.SHRP_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}_${{ steps.date.outputs.DATE_SHORT }}.img
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/SHRP_${{ github.event.inputs.SHRP_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}_${{ steps.date.outputs.DATE_SHORT }}.tar
          workspace/out/target/product/${{ github.event.inputs.DEVICE_NAME }}/SHRP_${{ github.event.inputs.SHRP_VERSION }}-${{ github.event.inputs.DEVICE_NAME }}_${{ steps.date.outputs.DATE_SHORT }}.zip
        name: shrp-${{ github.event.inputs.DEVICE_NAME }}-${{ steps.date.outputs.DATE_SHORT }}
        tag_name: ${{ steps.date.outputs.DATE_TAG }}
        body: |
          Manifest: ${{ github.event.inputs.MANIFEST_BRANCH }}
          Device: ${{ github.event.inputs.DEVICE_NAME }}
          Target: ${{ github.event.inputs.BUILD_TARGET }}
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
